language: python
os: linux
dist: jammy

python:
  - "3.11"

cache: pip

install:
  - pip install --upgrade pip || true
  - pip install snscrape || true

env:
  global:
    - DRY_RUN=1
    - HANDLES="BillAckman"

script:
  - set +e
  - python -c "import snscrape.modules.twitter as snt; print('snscrape OK')" || true
  - if [ -f ackman-alert.py ]; then python ackman-alert.py --once --notify-on-first || true; else echo "ackman-alert.py missing (ok)"; fi
  - true
