language: python
os: linux
dist: jammy

python:
  - "3.11"
  - "3.10"

cache: pip

env:
  global:
    - HANDLES="BillAckman"
    - DRY_RUN=1

stages:
  - name: lint
  - name: smoke

jobs:
  include:
    - stage: lint
      name: "Lint: flake8"
      install:
        - pip install --upgrade pip
        - pip install flake8
      script:
        - if [ -f ackman-alert.py ]; then flake8 ackman-alert.py; else echo "ackman-alert.py not found, skipping"; fi

    - stage: smoke
      name: "Smoke: import snscrape & dry-run ackman-alert.py"
      install:
        - pip install --upgrade pip
        - pip install snscrape
      script:
        - python -c "import snscrape.modules.twitter as snt; print('snscrape OK')"
        - if [ -f ackman-alert.py ]; then python ackman-alert.py --once --notify-on-first || true; else echo "ackman-alert.py missing"; fi
